inherit: true

build:
  environment:
      php: 8.1
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [src/*, tests/*]
