name: PHPUnit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run:
    name: PHP ${{ matrix.php-versions }} Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.repository == 'CSoellinger/silverstripe-limit-characters-with-html' || github.event_name == 'pull_request' }}

    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: phpunit:9.5
        # env:
        #   COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last Monday's date
        id: get-date
        run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> $GITHUB_OUTPUT

      - name: Check PHP Version
        run: php -v

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          custom-cache-suffix: ${{ steps.get-date.outputs.date }}

      - name: Run test suite
        run: composer run-script test
